exclude: '^deps/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v22.1.4'
    hooks:
    - id: clang-format
      types_or: [c++, c, header]

  - repo: local
    hooks:
        - id: clang-tidy-docker
          name: clang-tidy-docker
          entry: docker compose run --rm -v .:/src -w /src builder clang-tidy
          language: system
          types_or: [c++, c, header]
          args: [
            "-extra-arg=-std=c++23",
            "-extra-arg=-D_GNU_SOURCE",
            "-extra-arg=-Ideps",
            "-extra-arg=-Iinclude",
            "-extra-arg=-I/usr/include",
            "-extra-arg=-include",
            "-extra-arg=cstdio"
          ]
